name: Validate Issue Implementation

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: read

jobs:
  validate-issues:
    runs-on: ubuntu-latest
    name: Validate PR implements referenced issues
    steps:
      - name: Validate Issue Implementation
        uses: augmentcode/issue-review-pr@v0
        with:
          augment_session_auth: ${{ secrets.AUGMENT_SESSION_AUTH }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_number: ${{ github.event.pull_request.number }}
          repo_name: ${{ github.repository }}

